version: 0.0
os: linux
files:
  - source: /myweb.war
    destination: /opt/tomcat7/webapps
hooks:
  BeforeInstall:
    - location: stop_tomcat.sh
  AfterInstall:
    - location: start_tomcat.sh
      timeout: 30
